language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - yarn build
env:
  - NODE_ENV=production
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
